version: 6
jobs:
- name: gradle ci
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: detect build version
    image: '@script:builtin:gradle:determine-docker-image@'
    commands:
    - echo "Detecting project version (may require some time while downloading gradle
      dependencies)..."
    - 'echo $(gradle properties | grep ^version: | grep -v unspecified | cut -c10-)
      > buildVersion'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildVersionStep
    name: set build version
    buildVersion: '@file:buildVersion@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run gradle
    image: '@script:builtin:gradle:determine-docker-image@'
    commands:
    - gradle build
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250m
  memoryRequirement: 128m
  caches:
  - key: gradle-cache
    path: /home/gradle/.gradle
  timeout: 3600
